fastvim/fastvim

README.md
Added new way to install and fixed the installations problems.
=> Changed the README.md due to installation problems.

ftplugin/java.lua
- [x ] New feature
- [ x] I have read and followed the [CONTRIBUTING.md](CONTRIBUTING.md) guidelines for this project.
- [ x] Added or updated documentation, changelog, news and if needed (e.g., `README.md`, code comments).
- [ x] I tested my modifications and they didn't cause any problems.
- [ x] My commit follows the project conventions
Add a configuration for the java lsp
=> feat: add java support

README.md, init.lua, lazy-lock.json, lua/configs/ui/alpha.lua
=> 📝 Improving doc removing redundant words

README.md
=> 📝 Improving documentation introduction

CHANGELOG.md, init.lua, lazy-lock.json, lua/configs/editor/lazydo.lua, lua/plugins/init.lua
=> feat: adding lazydo config support

README.md, init.lua, lua/modules/starter/init.lua
Added the file starter module that creates a class for an empty java file when started, inspired by the practicality of intellij designed specifically for java developers that can be expanded to something larger.
=> feat: added file starter

CHANGELOG.md, README.md, init.lua, lua/modules/handlers/init.lua, lua/modules/loader/init.lua
=> feat: adding theme switcher handler

README.md
=> 🐛 Fixxing readme format

README.md, lua/configs/lsp/utils.lua
=> updating tasklist

CHANGELOG.md
=> 📝 Updating changelog

lua/configs/lsp/html.lua, lua/configs/lsp/ts_ls.lua, lua/plugins/init.lua
=> adding typescript tools support and improving variable names

.github/workflows/lua.yaml
=> ✨ Adding ci workflows

CHANGELOG.md, init.lua, lazy-lock.json, lua/configs/treesitter.lua, lua/modules/snippets/init.lua, lua/modules/snippets/snippets.lua
=> adding snippets and updating treesitter config

README.md, lua/configs/lsp/angular.lua, lua/configs/lsp/init.lua, lua/configs/lsp/vue.lua, lua/modules/snippets/init.lua
=> Adding lsp config for vue and angular

CHANGELOG.md, README.md, lua/configs/lsp/astro.lua, lua/configs/lsp/init.lua, lua/configs/lsp/python.lua, lua/configs/lsp/svelte.lua
=> Adding new lsp's on config

lua/modules/handlers/init.lua
=> 🔥 Adding more logs

README.md, doc/getting_started.norg, init.lua, lua/core/functions.lua, lua/plugins/init.lua
=> ✨ Adding see docs function

README.md, lua/configs/blink-cmp.lua, lua/configs/cmp.lua, lua/configs/colorful-menu.lua, lua/core/functions.lua, lua/core/mappings.lua, lua/plugins/init.lua
=> revert changes

README.md, lua/core/options.lua
=> Adding keymaps in doc

README.md, lua/configs/cmp.lua
=> Fixxing error: /home/charon/.config/nvim/lua/configs/cmp.lua:81:  attempt to index field 'config' (a nil value) in cmp config
